import { ImageResponse } from "next/og";

export const alt = "Imagination Arts — art classes in Ardenwood, Fremont";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default function OpenGraphImage() {
  return new ImageResponse(<div style={{ width: "100%", height: "100%", display: "flex", position: "relative", overflow: "hidden", background: "#fff8e9", color: "#27344a", padding: "68px 76px", fontFamily: "Arial" }}><div style={{ display: "flex", flexDirection: "column", justifyContent: "space-between", width: "68%" }}><div style={{ display: "flex", alignItems: "center", fontSize: 28, fontWeight: 800 }}><span style={{ display: "flex", marginRight: 14, width: 38, height: 38, alignItems: "center", justifyContent: "center", borderRadius: "50%", background: "#f8c74d" }}>+</span>Imagination Arts</div><div style={{ display: "flex", flexDirection: "column" }}><div style={{ color: "#9b609e", fontSize: 22, letterSpacing: 3, fontWeight: 800 }}>ARDENWOOD · FREMONT</div><div style={{ marginTop: 22, fontSize: 66, lineHeight: 1.02, letterSpacing: -4, fontWeight: 900 }}>Big imaginations start with one colorful idea.</div></div><div style={{ fontSize: 25 }}>Art classes for artists ages four and up</div></div><div style={{ position: "absolute", right: 62, top: 83, width: 320, height: 390, background: "#fffdf8", borderRadius: "10px 32px 12px 38px", transform: "rotate(7deg)", display: "flex", overflow: "hidden" }}><div style={{ position: "absolute", left: 22, top: 65, width: 170, height: 135, borderRadius: "48% 52% 40% 60%", background: "#f26f61", transform: "rotate(-20deg)" }} /><div style={{ position: "absolute", right: 16, top: 135, width: 170, height: 210, borderRadius: "52% 45% 60% 40%", background: "#7ec7e9", transform: "rotate(26deg)" }} /><div style={{ position: "absolute", left: 70, bottom: 30, width: 130, height: 93, borderRadius: "48% 52% 60% 40%", background: "#f8c74d", transform: "rotate(17deg)" }} /></div></div>, size);
}
