"use client";

import { FormEvent, useMemo, useState } from "react";
import { contact, programs } from "@/lib/site-data";

type Inquiry = { name: string; email: string; phone: string; artistAge: string; program: string; contactMethod: string; availability: string; message: string };
const initialInquiry: Inquiry = { name: "", email: "", phone: "", artistAge: "", program: "", contactMethod: "Email", availability: "", message: "" };

export function InquiryComposer() {
  const [inquiry, setInquiry] = useState<Inquiry>(initialInquiry);
  const [prepared, setPrepared] = useState(false);
  const message = useMemo(() => `Hello Imagination Arts,\n\nI’d like to ask about a trial class.\n\nParent / adult name: ${inquiry.name}\nEmail: ${inquiry.email}\nPhone: ${inquiry.phone}\nArtist age or grade: ${inquiry.artistAge}\nInterested in: ${inquiry.program || "Not sure yet"}\nPreferred contact: ${inquiry.contactMethod}\nBest days / times: ${inquiry.availability || "Not provided"}\n\nAnything else we should know?\n${inquiry.message || "—"}\n\nThank you!`, [inquiry]);
  const emailHref = `mailto:${contact.email}?subject=${encodeURIComponent("Trial class inquiry")}&body=${encodeURIComponent(message)}`;
  const smsHref = `sms:${contact.phoneInternational}?&body=${encodeURIComponent(message)}`;
  const update = (field: keyof Inquiry, value: string) => { setInquiry((current) => ({ ...current, [field]: value })); setPrepared(false); };
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setPrepared(true); };

  return <form className="inquiry-form" onSubmit={submit}><p className="eyebrow">Trial inquiry</p><h2>Tell us about your artist.</h2><p className="form-intro">We&apos;ll prepare your note for email or text. Your details are not stored on this website.</p><div className="form-grid"><div className="field"><label htmlFor="name">Parent / adult name</label><input id="name" required value={inquiry.name} onChange={(e) => update("name", e.target.value)} /></div><div className="field"><label htmlFor="artistAge">Artist age or grade</label><input id="artistAge" required placeholder="For example: 7 or 3rd grade" value={inquiry.artistAge} onChange={(e) => update("artistAge", e.target.value)} /></div><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" required value={inquiry.email} onChange={(e) => update("email", e.target.value)} /></div><div className="field"><label htmlFor="phone">Phone</label><input id="phone" type="tel" required value={inquiry.phone} onChange={(e) => update("phone", e.target.value)} /></div><div className="field"><label htmlFor="program">What interests you?</label><select id="program" value={inquiry.program} onChange={(e) => update("program", e.target.value)}><option value="">I&apos;m not sure yet</option>{programs.map((program) => <option key={program.slug}>{program.name}</option>)}<option>Camp or workshop</option><option>Birthday party</option></select></div><div className="field"><label htmlFor="contactMethod">Best way to reply</label><select id="contactMethod" value={inquiry.contactMethod} onChange={(e) => update("contactMethod", e.target.value)}><option>Email</option><option>Phone call</option><option>Text message</option></select></div><div className="field field--full"><label htmlFor="availability">Best days or times</label><input id="availability" placeholder="For example: weekday afternoons or Saturday mornings" value={inquiry.availability} onChange={(e) => update("availability", e.target.value)} /></div><div className="field field--full"><label htmlFor="message">Anything else you&apos;d like to share?</label><textarea id="message" value={inquiry.message} onChange={(e) => update("message", e.target.value)} /></div></div><div className="form-actions"><button className="button button--coral" type="submit">Prepare my inquiry</button><p className="form-note">Nothing is sent until you choose email or text.</p></div>{prepared && <div className="prepared-message" aria-live="polite"><h3>Your message is ready.</h3><p>Choose how you&apos;d like to send it. A new message will open with your details filled in.</p><div className="button-row"><a className="button button--ink" href={emailHref}>Send by email</a><a className="button button--outline" href={smsHref}>Send by text</a></div></div>}</form>;
}
